### ISSUE TITLE
UI # 需要图标rent roll，刚刚发现还有缺失，请更新iconfont

### ISSUE THREAD

**Issue by paulatgh** [zillyinc/support#1]
如题，请出图

**Comment by paulatgh** [comment]
![image](https://user-images.githubusercontent.com/48198634/64109993-778bc700-cdb3-11e9-96a4-5bc223b82916.png)

**Comment by paulatgh** [comment]
请UI同学，给我具体的下载地址，我们可以马上更新UI库

**Comment by itomrachev** [comment]
@paulatgh https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.11&manage_type=myprojects&projectId=1287081

**Comment by itomrachev** [comment]
@paulatgh 
![image](https://user-images.githubusercontent.com/38903785/64173859-c9535080-ce8a-11e9-8d94-df842e1991ac.png)
we provided access to it and said about it to all of these people

**Comment by paulatgh** [comment]
重新更新icon库，需要4个小时的工作量；本周全力冲刺onboarding，新旧版本融合上线，lease和chat的UI部分。9月6日下午或9月9日开始

**Comment by paulatgh** [comment]
9月4日下午找到icon包，更新了0.3.6；还有缺失问题新开issue，问题关闭
