### ISSUE TITLE
UI # 为什么图片与pdf不能用同一种上传方式

### ISSUE THREAD

**Issue by JerryChenQi** [zillyinc/support#5]
![image](https://user-images.githubusercontent.com/45622910/64254186-72647e80-cf51-11e9-8ca4-7ec490397bf3.png)

**Comment by itomrachev** [comment]
@JerryChenQi 左边红色框里的状态是当我拖拽文件（比如pdf）到灰色区域时但未松鼠标的状态

**Comment by itomrachev** [comment]
@JerryChenQi 右边框里的内容是文件已经上传的状态

**Comment by paulatgh** [comment]
@itomrachev 
明白了，那么文件个数、大小 是否有上限？ pdf中未做说明

**Comment by itomrachev** [comment]
@paulatgh  comment from product team: edge case issue, no limit for now. Once T has time to look at the code he will make that decision, but no need to worry about this for now

**Comment by paulatgh** [comment]
OK 问题搞清，关闭issue
