### ISSUE TITLE
UI # 缺少图标

### ISSUE THREAD

**Issue by webbHou** [zillyinc/support#6]
目前图标库缺少这几个图标

![image](https://user-images.githubusercontent.com/25664474/64252254-fa945500-cf4c-11e9-9258-bca78f4cd627.png)

![image](https://user-images.githubusercontent.com/25664474/64252559-e0a74200-cf4d-11e9-869a-e81aa52e219a.png)

![image](https://user-images.githubusercontent.com/25664474/64254360-ce2f0780-cf51-11e9-81f2-4f104f54de77.png)

**Comment by dradetsky** [comment]
@webbHou ?

**Comment by webbHou** [comment]
Sorry, @ wrong person.

**Comment by paulatgh** [comment]
还有缺失，只能通过线下沟通的方式来做。
